[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data = {path = "../data"}
pest = "2.3.0"
pest_derive = "2.3.0"